# Generated by Django 3.0.3 on 2020-11-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freefollowers',
            old_name='user',
            new_name='owner',
        ),
    ]
