# Generated by Django 3.0.3 on 2021-05-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201121_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default='False', verbose_name='hidden'),
        ),
    ]
