# Generated by Django 3.0.3 on 2021-05-17 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hidden',
        ),
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.ManyToManyField(blank=True, related_name='hidden', to=settings.AUTH_USER_MODEL),
        ),
    ]
