# Generated by Django 3.0.3 on 2020-11-12 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=150, verbose_name='Ranked Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='1.jpg', upload_to='displays', verbose_name='Avatar')),
                ('background', models.ImageField(blank=True, default='ak.jpg', upload_to='backgrounds', verbose_name='background1')),
                ('background_2', models.ImageField(blank=True, default='ak.jpg', upload_to='backgrounds', verbose_name='background2')),
                ('background_3', models.ImageField(blank=True, default='ak.jpg', upload_to='backgrounds', verbose_name='background3')),
                ('background_4', models.ImageField(blank=True, default='ak.jpg', upload_to='backgrounds', verbose_name='background4')),
                ('background_5', models.ImageField(blank=True, default='ak.jpg', upload_to='backgrounds', verbose_name='background5')),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('displayname', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True, default='I like something')),
                ('close_friends', models.ManyToManyField(blank=True, related_name='my_close_friends', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ManyToManyField(blank=True, related_name='is_following', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ManyToManyField(blank=True, default='beginner', related_name='rank', to='profiles.Rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
