# Generated by Django 3.0.3 on 2020-11-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201112_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
