# Generated by Django 3.0.3 on 2020-11-13 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rank_date_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='date_create',
            new_name='create_date',
        ),
    ]
