# Generated by Django 3.0.3 on 2020-11-13 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201112_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
