# Generated by Django 3.0.3 on 2021-05-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20210511_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='I like something', max_length=255, verbose_name='bio'),
        ),
    ]
