# Generated by Django 3.0.3 on 2021-05-19 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20210519_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='1.jpg', null=True, upload_to='displays', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background',
            field=models.ImageField(blank=True, default='ak.jpg', null=True, upload_to='backgrounds', verbose_name='background1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_2',
            field=models.ImageField(blank=True, default='ak.jpg', null=True, upload_to='backgrounds', verbose_name='background2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_3',
            field=models.ImageField(blank=True, default='ak.jpg', null=True, upload_to='backgrounds', verbose_name='background3'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_4',
            field=models.ImageField(blank=True, default='ak.jpg', null=True, upload_to='backgrounds', verbose_name='background4'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='background_5',
            field=models.ImageField(blank=True, default='ak.jpg', null=True, upload_to='backgrounds', verbose_name='background5'),
        ),
    ]
