# Generated by Django 3.0.3 on 2021-07-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20210519_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='displayname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
